dataset:
  observation_fieldnames:
     - index
     - sentence
     - lemma_sentence
     - upos_sentence
     - xpos_sentence
     - morph
     - head_indices
     - governance_relations
     - secondary_relations
     - extra_info
     - head_dep_pair
     - embeddings
  corpus:
    root: ../structural-probes/UD_English/
    train_path: en-ud-train.conllu
    dev_path: en-ud-dev.conllu
    test_path: en-ud-test.conllu
    label_path: bc_labels.pkl
  embeddings:
    type: token #{token,subword}
    root: ../structural-probes/UD_English/ 
    train_path: en-ud-train.bert-layers-1-6-768
    dev_path: en-ud-dev.bert-layers-1-6-768
    test_path: en-ud-test.bert-layers-1-6-768
  batch_size: 40
model:
  use_disk: True
  pos:
    hidden_dim: 768 # ELMo hidden dim
    #embedding_dim: 1024 # ELMo word embedding dim
    model_type: bert-disk # BERT-disk, ELMo-disk, 
    use_disk: True
    model_layer: 1 # BERT-base: {1,...,12}; ELMo: {1,2,3}
    class_number: 22
  ner:
    hidden_dim: 768 # ELMo hidden dim
    #embedding_dim: 1024 # ELMo word embedding dim
    model_type: ELMo-disk # BERT-disk, ELMo-disk, 
    use_disk: True
    model_layer: 1 # BERT-base: {1,...,12}; ELMo: {1,2,3}
    class_number: 19
  srl:
    hidden_dim: 1536 # 2*ELMo hidden dim, [predicate, argument]
    #embedding_dim: 1024 # ELMo word embedding dim
    model_type: ELMo-disk # BERT-disk, ELMo-disk, 
    use_disk: True
    model_layer: 1 # BERT-base: {1,...,12}; ELMo: {1,2,3}
    class_number: 20
  dep:
    hidden_dim: 1536 # 2*ELMo hidden dim, [predicate, argument]
    #embedding_dim: 1024 # ELMo word embedding dim
    model_type: ELMo-disk # BERT-disk, ELMo-disk, 
    use_disk: True
    model_layer: 1 # BERT-base: {1,...,12}; ELMo: {1,2,3}
    class_number: 35
device: cuda
reporting:
  root: results/results_ontonotes/all_layer_of_bert/null_Ps_layer2/
  params_path: classifier.params
  observation_paths:
    train_path: train.observations
    dev_path: dev.observations
    test_path: test.observations
  prediction_paths:
    train_path: train.predictions
    dev_path: dev.predictions
    test_path: test.predictions